### ISSUE TITLE
Generating UUID's in browser

### ISSUE THREAD

**Issue by justmobilize** [keen/keen-tracking.js#36]
for ```getUniqueId``` I've seen a few people dislike the standard Math.random() we get in most browsers. This is the snippet we've used for generating a uuid: https://github.com/broofa/node-uuid/blob/master/uuid.js

**Comment by dustinlarimer** [comment]
@justmobilize thanks for weighing in! I really like that lib too, but opted for borrowing this [compact generator](http://stackoverflow.com/questions/105034/create-guid-uuid-in-javascript/2117523#2117523) (also by broofa!) to minimize the overall dependency footprint. Happy to leave this issue open for awhile, to see if there is more interest in using a more robust library instead of what's in there now.
